// <auto-generated />
using System;
using Backend_Amethyst_Audio.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend_Amethyst_Audio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411081645_ChangePlaylistInfo")]
    partial class ChangePlaylistInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Album", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CoverFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cover_file_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_albums_id");

                    b.ToTable("albums", "collections");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.AlbumsAuthor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdAlbum")
                        .HasColumnType("bigint")
                        .HasColumnName("id_album");

                    b.Property<long>("IdAuthor")
                        .HasColumnType("bigint")
                        .HasColumnName("id_author");

                    b.HasKey("Id")
                        .HasName("pk_album_authors_id");

                    b.HasIndex("IdAuthor");

                    b.HasIndex(new[] { "IdAlbum", "IdAuthor" }, "uq_albums_authors")
                        .IsUnique();

                    b.ToTable("albums_authors", "collections");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.AlbumsTrack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("IdAlbum")
                        .HasColumnType("bigint")
                        .HasColumnName("id_album");

                    b.Property<long>("IdTrack")
                        .HasColumnType("bigint")
                        .HasColumnName("id_track");

                    b.HasKey("Id")
                        .HasName("pk_albums_tracks_id");

                    b.HasIndex("IdTrack");

                    b.HasIndex(new[] { "IdAlbum", "IdTrack" }, "uq_albums_tracks")
                        .IsUnique();

                    b.ToTable("albums_tracks", "collections");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.AuthEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ExternalId")
                        .HasColumnType("bigint")
                        .HasColumnName("external_id");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("integer")
                        .HasColumnName("id_employee");

                    b.Property<short>("IdProvider")
                        .HasColumnType("smallint")
                        .HasColumnName("id_provider");

                    b.HasKey("Id")
                        .HasName("pk_auth_employees_id");

                    b.HasIndex("IdProvider");

                    b.HasIndex(new[] { "IdEmployee", "IdProvider" }, "uq_auth_employees_employee_provider")
                        .IsUnique();

                    b.ToTable("auth_employees", "auth");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.AuthProvider", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_name");

                    b.HasKey("Id")
                        .HasName("pk_auth_providers_id");

                    b.ToTable("auth_providers", "auth");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.AuthUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExternalId")
                        .HasColumnType("bigint")
                        .HasColumnName("external_id");

                    b.Property<short>("IdProvider")
                        .HasColumnType("smallint")
                        .HasColumnName("id_provider");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint")
                        .HasColumnName("id_user");

                    b.HasKey("Id")
                        .HasName("pk_auth_users_id");

                    b.HasIndex("IdProvider");

                    b.HasIndex(new[] { "IdUser", "IdProvider" }, "uq_auth_users_id_user_id_provider")
                        .IsUnique();

                    b.ToTable("auth_users", "auth");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<short>("IdRole")
                        .HasColumnType("smallint")
                        .HasColumnName("id_role");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastVisit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_visit")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Lastname")
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_employees_id");

                    b.HasIndex("IdRole");

                    b.HasIndex(new[] { "Email" }, "uq_employees_email")
                        .IsUnique();

                    b.ToTable("employees", "admin");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Genre", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("genre_name");

                    b.HasKey("Id")
                        .HasName("pk_genres_id");

                    b.ToTable("genres", "content");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.LibrariesTrack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("IdLibrary")
                        .HasColumnType("bigint")
                        .HasColumnName("id_library");

                    b.Property<long>("IdTrack")
                        .HasColumnType("bigint")
                        .HasColumnName("id_track");

                    b.HasKey("Id")
                        .HasName("pk_libraries_tracks_id");

                    b.HasIndex("IdTrack");

                    b.HasIndex(new[] { "IdLibrary", "IdTrack" }, "uq_libraries_tracks")
                        .IsUnique();

                    b.ToTable("libraries_tracks", "collections");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Library", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint")
                        .HasColumnName("id_user");

                    b.HasKey("Id")
                        .HasName("pk_libraries_id");

                    b.HasIndex("IdUser");

                    b.ToTable("libraries", "collections");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Mood", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("MoodName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mood_name");

                    b.HasKey("Id")
                        .HasName("pk_moods_id");

                    b.ToTable("moods", "content");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short>("IdType")
                        .HasColumnType("smallint")
                        .HasColumnName("id_type");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint")
                        .HasColumnName("id_user");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_notifications_id");

                    b.HasIndex("IdType");

                    b.HasIndex("IdUser");

                    b.ToTable("notifications", "users");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Pace", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("PaceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pace_name");

                    b.HasKey("Id")
                        .HasName("pk_paces_id");

                    b.ToTable("paces", "content");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Playlist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CoverFileName")
                        .HasColumnType("text")
                        .HasColumnName("cover_file_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint")
                        .HasColumnName("id_user");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_playlists_id");

                    b.HasIndex("IdUser");

                    b.ToTable("playlists", "collections");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.PlaylistsTrack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("IdPlaylist")
                        .HasColumnType("bigint")
                        .HasColumnName("id_playlist");

                    b.Property<long>("IdTrack")
                        .HasColumnType("bigint")
                        .HasColumnName("id_track");

                    b.HasKey("Id")
                        .HasName("pk_playlists_tracks_id");

                    b.HasIndex("IdTrack");

                    b.HasIndex(new[] { "IdPlaylist", "IdTrack" }, "uq_playlists_tracks")
                        .IsUnique();

                    b.ToTable("playlists_tracks", "collections");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Reason", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("ReasonName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason_name");

                    b.HasKey("Id")
                        .HasName("pk_types_reason_id");

                    b.ToTable("reasons", "moderation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Report", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Discription")
                        .HasColumnType("text")
                        .HasColumnName("discription");

                    b.Property<short>("IdReason")
                        .HasColumnType("smallint")
                        .HasColumnName("id_reason");

                    b.Property<short>("IdType")
                        .HasColumnType("smallint")
                        .HasColumnName("id_type");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint")
                        .HasColumnName("id_user");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.HasKey("Id")
                        .HasName("pk_reports_id");

                    b.HasIndex("IdReason");

                    b.HasIndex("IdType");

                    b.HasIndex("IdUser");

                    b.ToTable("reports", "moderation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.ReportAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("integer")
                        .HasColumnName("id_employee");

                    b.Property<long>("IdReport")
                        .HasColumnType("bigint")
                        .HasColumnName("id_report");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.HasKey("Id")
                        .HasName("pk_report_answers_id");

                    b.HasIndex("IdEmployee");

                    b.HasIndex("IdReport");

                    b.ToTable("report_answers", "moderation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Role", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.HasKey("Id")
                        .HasName("pk_roles_id");

                    b.ToTable("roles", "admin");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.SavedAlbum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdAlbum")
                        .HasColumnType("bigint")
                        .HasColumnName("id_album");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint")
                        .HasColumnName("id_user");

                    b.HasKey("Id")
                        .HasName("pk_album_users_id");

                    b.HasIndex("IdUser");

                    b.HasIndex(new[] { "IdAlbum", "IdUser" }, "uq_album_users")
                        .IsUnique();

                    b.ToTable("saved_albums", "collections");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.SavedPlaylist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdPlaylist")
                        .HasColumnType("bigint")
                        .HasColumnName("id_playlist");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint")
                        .HasColumnName("id_user");

                    b.HasKey("Id")
                        .HasName("pk_playlists_users_id");

                    b.HasIndex("IdUser");

                    b.HasIndex(new[] { "IdPlaylist", "IdUser" }, "uq_playlists_users")
                        .IsUnique();

                    b.ToTable("saved_playlists", "collections");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Track", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("CoverFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cover_file_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DurationSec")
                        .HasColumnType("integer")
                        .HasColumnName("duration_sec");

                    b.Property<short?>("IdMood")
                        .HasColumnType("smallint")
                        .HasColumnName("id_mood");

                    b.Property<short?>("IdPace")
                        .HasColumnType("smallint")
                        .HasColumnName("id_pace");

                    b.Property<bool>("IsExplicit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_explicit");

                    b.Property<bool?>("IsTextless")
                        .HasColumnType("boolean")
                        .HasColumnName("is_textless");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TrackFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("track_file_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_tracks_id");

                    b.HasIndex("IdMood");

                    b.HasIndex("IdPace");

                    b.HasIndex(new[] { "Name" }, "uq_tracks_name")
                        .IsUnique();

                    b.ToTable("tracks", "content");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.TracksAuthor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdAuthor")
                        .HasColumnType("bigint")
                        .HasColumnName("id_author");

                    b.Property<long>("IdTrack")
                        .HasColumnType("bigint")
                        .HasColumnName("id_track");

                    b.HasKey("Id")
                        .HasName("pk_tracks_authors_id");

                    b.HasIndex("IdAuthor");

                    b.HasIndex("IdTrack");

                    b.ToTable("tracks_authors", "content");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.TracksGenre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("IdGenre")
                        .HasColumnType("smallint")
                        .HasColumnName("id_genre");

                    b.Property<long>("IdTrack")
                        .HasColumnType("bigint")
                        .HasColumnName("id_track");

                    b.HasKey("Id")
                        .HasName("pk_track_genres_id");

                    b.HasIndex("IdGenre");

                    b.HasIndex(new[] { "IdTrack", "IdGenre" }, "uq_track_genres")
                        .IsUnique();

                    b.ToTable("tracks_genres", "content");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.TypesNotification", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_name");

                    b.HasKey("Id")
                        .HasName("pk_types_notifications_id");

                    b.ToTable("types_notifications", "users");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.TypesReport", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_name");

                    b.HasKey("Id")
                        .HasName("pk_types_report_id");

                    b.ToTable("types_report", "moderation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarFileName")
                        .HasColumnType("text")
                        .HasColumnName("avatar_file_name");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("HeaderFileName")
                        .HasColumnType("text")
                        .HasColumnName("header_file_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_verified");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<DateTime>("LastVisit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_visit")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Lastname")
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_users_id");

                    b.HasIndex(new[] { "Email" }, "uq_users_email")
                        .IsUnique();

                    b.HasIndex(new[] { "Nickname" }, "uq_users_nickname")
                        .IsUnique();

                    b.ToTable("users", "users");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.UsersHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdTrack")
                        .HasColumnType("bigint")
                        .HasColumnName("id_track");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint")
                        .HasColumnName("id_user");

                    b.Property<DateTime>("ListeningAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("listening_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("TotalListeningSec")
                        .HasColumnType("integer")
                        .HasColumnName("total_listening_sec");

                    b.HasKey("Id")
                        .HasName("pk_tracks_users_id");

                    b.HasIndex("IdTrack");

                    b.HasIndex(new[] { "IdUser", "IdTrack" }, "uk_users_history")
                        .IsUnique();

                    b.ToTable("users_history", "users");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.UsersSub", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdSubscriber")
                        .HasColumnType("bigint")
                        .HasColumnName("id_subscriber");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint")
                        .HasColumnName("id_user");

                    b.Property<DateTime>("SubscribedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscribed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_users_subs_id");

                    b.HasIndex("IdSubscriber");

                    b.HasIndex(new[] { "IdUser", "IdSubscriber" }, "uq_users_subs_id_user_id_subscriber")
                        .IsUnique();

                    b.ToTable("users_subs", "users");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.AlbumsAuthor", b =>
                {
                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.Album", "IdAlbumNavigation")
                        .WithMany("AlbumsAuthors")
                        .HasForeignKey("IdAlbum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_albums_authors_id_album");

                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.User", "IdAuthorNavigation")
                        .WithMany("AlbumsAuthors")
                        .HasForeignKey("IdAuthor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_albums_authors_id_author");

                    b.Navigation("IdAlbumNavigation");

                    b.Navigation("IdAuthorNavigation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.AlbumsTrack", b =>
                {
                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.Album", "IdAlbumNavigation")
                        .WithMany("AlbumsTracks")
                        .HasForeignKey("IdAlbum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_albums_tracks_id_album");

                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.Track", "IdTrackNavigation")
                        .WithMany("AlbumsTracks")
                        .HasForeignKey("IdTrack")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_albums_tracks_id_track");

                    b.Navigation("IdAlbumNavigation");

                    b.Navigation("IdTrackNavigation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.AuthEmployee", b =>
                {
                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.Employee", "IdEmployeeNavigation")
                        .WithMany("OauthEmployees")
                        .HasForeignKey("IdEmployee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_oauth_employees_id_employee");

                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.AuthProvider", "IdProviderNavigation")
                        .WithMany("OauthEmployees")
                        .HasForeignKey("IdProvider")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_oauth_users_id_provider");

                    b.Navigation("IdEmployeeNavigation");

                    b.Navigation("IdProviderNavigation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.AuthUser", b =>
                {
                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.AuthProvider", "IdProviderNavigation")
                        .WithMany("OauthUsers")
                        .HasForeignKey("IdProvider")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_oauth_users_id_provider");

                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.User", "IdUserNavigation")
                        .WithMany("OauthUsers")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_oauth_users_id_user");

                    b.Navigation("IdProviderNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Employee", b =>
                {
                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.Role", "IdRoleNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employees_id_role");

                    b.Navigation("IdRoleNavigation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.LibrariesTrack", b =>
                {
                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.Library", "IdLibraryNavigation")
                        .WithMany("LibrariesTracks")
                        .HasForeignKey("IdLibrary")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_libraries_tracks_id_library");

                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.Track", "IdTrackNavigation")
                        .WithMany("LibrariesTracks")
                        .HasForeignKey("IdTrack")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_libraries_tracks_id_track");

                    b.Navigation("IdLibraryNavigation");

                    b.Navigation("IdTrackNavigation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Library", b =>
                {
                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.User", "IdUserNavigation")
                        .WithMany("Libraries")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_libraries_id_user");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Notification", b =>
                {
                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.TypesNotification", "IdTypeNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("IdType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_id_type");

                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.User", "IdUserNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_id_user");

                    b.Navigation("IdTypeNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Playlist", b =>
                {
                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.User", "IdUserNavigation")
                        .WithMany("Playlists")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlists_id_user");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.PlaylistsTrack", b =>
                {
                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.Playlist", "IdPlaylistNavigation")
                        .WithMany("PlaylistsTracks")
                        .HasForeignKey("IdPlaylist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlists_tracks_id_playlist");

                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.Track", "IdTrackNavigation")
                        .WithMany("PlaylistsTracks")
                        .HasForeignKey("IdTrack")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlists_tracks_id_track");

                    b.Navigation("IdPlaylistNavigation");

                    b.Navigation("IdTrackNavigation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Report", b =>
                {
                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.Reason", "IdReasonNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("IdReason")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reports_id_reason");

                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.TypesReport", "IdTypeNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("IdType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reports_id_type");

                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.User", "IdUserNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reports_id_user");

                    b.Navigation("IdReasonNavigation");

                    b.Navigation("IdTypeNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.ReportAnswer", b =>
                {
                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.Employee", "IdEmployeeNavigation")
                        .WithMany("ReportAnswers")
                        .HasForeignKey("IdEmployee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_answers_id_employee");

                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.Report", "IdReportNavigation")
                        .WithMany("ReportAnswers")
                        .HasForeignKey("IdReport")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_answers_id_report");

                    b.Navigation("IdEmployeeNavigation");

                    b.Navigation("IdReportNavigation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.SavedAlbum", b =>
                {
                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.Album", "IdAlbumNavigation")
                        .WithMany("SavedAlbums")
                        .HasForeignKey("IdAlbum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_album_users_id_album");

                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.User", "IdUserNavigation")
                        .WithMany("SavedAlbums")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_albums_users_id_user");

                    b.Navigation("IdAlbumNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.SavedPlaylist", b =>
                {
                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.Playlist", "IdPlaylistNavigation")
                        .WithMany("SavedPlaylists")
                        .HasForeignKey("IdPlaylist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlists_users_id_playlist");

                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.User", "IdUserNavigation")
                        .WithMany("SavedPlaylists")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlists_users_id_user");

                    b.Navigation("IdPlaylistNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Track", b =>
                {
                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.Mood", "IdMoodNavigation")
                        .WithMany("Tracks")
                        .HasForeignKey("IdMood")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tracks_id_mood");

                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.Pace", "IdPaceNavigation")
                        .WithMany("Tracks")
                        .HasForeignKey("IdPace")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tracks_id_pace");

                    b.Navigation("IdMoodNavigation");

                    b.Navigation("IdPaceNavigation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.TracksAuthor", b =>
                {
                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.User", "IdAuthorNavigation")
                        .WithMany("TracksAuthors")
                        .HasForeignKey("IdAuthor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tracks_authors_id_author");

                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.Track", "IdTrackNavigation")
                        .WithMany("TracksAuthors")
                        .HasForeignKey("IdTrack")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tracks_authors_id_track");

                    b.Navigation("IdAuthorNavigation");

                    b.Navigation("IdTrackNavigation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.TracksGenre", b =>
                {
                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.Genre", "IdGenreNavigation")
                        .WithMany("TracksGenres")
                        .HasForeignKey("IdGenre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_genres_id_genre");

                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.Track", "IdTrackNavigation")
                        .WithMany("TracksGenres")
                        .HasForeignKey("IdTrack")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_genres_id_track");

                    b.Navigation("IdGenreNavigation");

                    b.Navigation("IdTrackNavigation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.UsersHistory", b =>
                {
                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.Track", "IdTrackNavigation")
                        .WithMany("UsersHistories")
                        .HasForeignKey("IdTrack")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tracks_users_id_track");

                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.User", "IdUserNavigation")
                        .WithMany("UsersHistories")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tracks_users_id_user");

                    b.Navigation("IdTrackNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.UsersSub", b =>
                {
                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.User", "IdSubscriberNavigation")
                        .WithMany("UsersSubIdSubscriberNavigations")
                        .HasForeignKey("IdSubscriber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_subs_id_subscriber");

                    b.HasOne("Backend_Amethyst_Audio.Models.Entities.User", "IdUserNavigation")
                        .WithMany("UsersSubIdUserNavigations")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_subs_id_user");

                    b.Navigation("IdSubscriberNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Album", b =>
                {
                    b.Navigation("AlbumsAuthors");

                    b.Navigation("AlbumsTracks");

                    b.Navigation("SavedAlbums");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.AuthProvider", b =>
                {
                    b.Navigation("OauthEmployees");

                    b.Navigation("OauthUsers");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Employee", b =>
                {
                    b.Navigation("OauthEmployees");

                    b.Navigation("ReportAnswers");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Genre", b =>
                {
                    b.Navigation("TracksGenres");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Library", b =>
                {
                    b.Navigation("LibrariesTracks");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Mood", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Pace", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Playlist", b =>
                {
                    b.Navigation("PlaylistsTracks");

                    b.Navigation("SavedPlaylists");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Reason", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Report", b =>
                {
                    b.Navigation("ReportAnswers");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Role", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.Track", b =>
                {
                    b.Navigation("AlbumsTracks");

                    b.Navigation("LibrariesTracks");

                    b.Navigation("PlaylistsTracks");

                    b.Navigation("TracksAuthors");

                    b.Navigation("TracksGenres");

                    b.Navigation("UsersHistories");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.TypesNotification", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.TypesReport", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Backend_Amethyst_Audio.Models.Entities.User", b =>
                {
                    b.Navigation("AlbumsAuthors");

                    b.Navigation("Libraries");

                    b.Navigation("Notifications");

                    b.Navigation("OauthUsers");

                    b.Navigation("Playlists");

                    b.Navigation("Reports");

                    b.Navigation("SavedAlbums");

                    b.Navigation("SavedPlaylists");

                    b.Navigation("TracksAuthors");

                    b.Navigation("UsersHistories");

                    b.Navigation("UsersSubIdSubscriberNavigations");

                    b.Navigation("UsersSubIdUserNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
